# Generated by Django 4.1.6 on 2023-02-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("refresh_token", "0002_auto_20190130_0900"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRefreshToken",
            fields=[],
            options={
                "verbose_name": "Refresh Token",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("refresh_token.refreshtoken",),
        ),
    ]
